### ISSUE TITLE
deviceToken是手机UDID,提示device token bytes must [32] length not [20]

### ISSUE THREAD

**Issue by sybortant** [teaey/apns4j#16]
deviceTokenString传入UDID,提示'
Exception in thread "main" cn.teaey.apns4j.protocol.InvalidDeviceTokenException: device token bytes must [32] length not [20]
	at cn.teaey.apns4j.ApnsHelper.checkDeviceToken(ApnsHelper.java:107)
	at cn.teaey.apns4j.network.ApnsChannel.send(ApnsChannel.java:121)
	at cn.teaey.apns4j.network.ApnsChannel.send(ApnsChannel.java:155)
	at cn.teaey.apns4j.network.ApnsChannel.send(ApnsChannel.java:179)
	at com.stylefeng.guns.rest.modular.push.service.impl.Push.main(Push.java:30)

**Comment by sybortant** [comment]
UDID 是 40位的字符串
